apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: springbootcamels.spring-boot-camel.eformat.me
spec:
  group: spring-boot-camel.eformat.me
  names:
    kind: SpringBootCamel
    listKind: SpringBootCamelList
    plural: springbootcamels
    singular: springbootcamel
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
